/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
    "./*.js"
  ],
  darkMode: "class",
  theme: {
      extend: {
          colors: {
              "surface-dim": "#131313",
              "secondary-container": "#1e95f2",
              "on-primary-fixed-variant": "#00530e",
              "on-secondary-fixed-variant": "#00497d",
              "error-container": "#93000a",
              "inverse-primary": "#006e16",
              "on-primary-fixed": "#002203",
              "secondary-fixed-dim": "#9ecaff",
              "tertiary-fixed-dim": "#ffb870",
              "surface-container-high": "#2a2a2a",
              "surface-container-lowest": "#0e0e0e",
              "background": "#131313",
              "surface-variant": "#353534",
              "on-error": "#690005",
              "error": "#ffb4ab",
              "on-tertiary-fixed-variant": "#693c00",
              "inverse-on-surface": "#313030",
              "on-surface": "#e5e2e1",
              "outline-variant": "#3b4b37",
              "surface-container-low": "#1c1b1b",
              "surface-container-highest": "#353534",
              "on-error-container": "#ffdad6",
              "outline": "#84967e",
              "secondary-fixed": "#d1e4ff",
              "tertiary-fixed": "#ffdcbe",
              "surface-container": "#201f1f",
              "on-surface-variant": "#b9ccb2",
              "surface-tint": "#00e639",
              "on-secondary": "#003258",
              "secondary": "#9ecaff",
              "on-tertiary-fixed": "#2c1600",
              "on-tertiary-container": "#8e5200",
              "primary-fixed-dim": "#00e639",
              "surface": "#131313",
              "on-secondary-fixed": "#001d36",
              "surface-bright": "#393939",
              "on-primary": "#003907",
              "primary-container": "#00ff41",
              "primary-fixed": "#72ff70",
              "inverse-surface": "#e5e2e1",
              "on-secondary-container": "#002b4d",
              "primary": "#ebffe2",
              "tertiary": "#fff8f4",
              "on-primary-container": "#007117",
              "tertiary-container": "#ffd5af",
              "on-tertiary": "#4a2800",
              "on-background": "#e5e2e1"
          },
          fontFamily: {
              "headline": ["Space Grotesk", "sans-serif"],
              "body": ["Inter", "sans-serif"],
              "label": ["Space Grotesk", "sans-serif"]
          },
          borderRadius: {"DEFAULT": "0px", "lg": "0px", "xl": "0px", "full": "9999px"},
      },
  },
  plugins: [],
}
