/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
    "./*.js"
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-tertiary-container": "#445269",
        "on-tertiary-fixed-variant": "#4e5c73",
        "secondary-container": "#393c3e",
        "on-primary-fixed-variant": "#006286",
        "tertiary-fixed": "#d4e3ff",
        "on-primary-fixed": "#00445e",
        "outline-variant": "#2b4680",
        "surface-container-high": "#031d4b",
        "secondary-fixed-dim": "#d3d4d7",
        "surface-dim": "#060e20",
        "tertiary-dim": "#c6d5f0",
        "primary-container": "#004c69",
        "on-primary": "#004560",
        "error": "#ee7d77",
        "on-secondary-fixed-variant": "#595c5e",
        "on-surface": "#dee5ff",
        "inverse-surface": "#faf8ff",
        "primary": "#7bd0ff",
        "tertiary-fixed-dim": "#c6d5f0",
        "on-error": "#490106",
        "tertiary-container": "#d4e3ff",
        "background": "#060e20",
        "tertiary": "#ebf1ff",
        "error-dim": "#bb5551",
        "secondary-dim": "#9c9ea0",
        "surface-bright": "#002867",
        "secondary-fixed": "#e1e2e5",
        "surface-variant": "#00225a",
        "surface-container-lowest": "#000000",
        "on-secondary-container": "#bebfc2",
        "primary-fixed-dim": "#a2dcff",
        "surface-container-highest": "#00225a",
        "on-surface-variant": "#91aaeb",
        "on-secondary-fixed": "#3d4042",
        "surface-tint": "#7bd0ff",
        "on-tertiary": "#4c5b72",
        "surface-container": "#05183c",
        "primary-fixed": "#c4e7ff",
        "inverse-on-surface": "#4d556b",
        "on-background": "#dee5ff",
        "on-secondary": "#1e2022",
        "primary-dim": "#47c4ff",
        "surface-container-low": "#06122d",
        "on-primary-container": "#97d8ff",
        "secondary": "#9c9ea0",
        "error-container": "#7f2927",
        "surface": "#060e20",
        "on-tertiary-fixed": "#324056",
        "on-error-container": "#ff9993",
        "outline": "#5b74b1",
        "inverse-primary": "#00668b"
      },
      fontFamily: {
        "headline": ["Inter", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Space Grotesk", "monospace"]
      },
      borderRadius: {"DEFAULT": "0.125rem", "lg": "0.25rem", "xl": "0.5rem", "full": "0.75rem"},
    },
  },
  plugins: [],
}
